name: Build

on:
  push:
  pull_request:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Setup Environment
        id: setup
        run: |
          echo "REPOSITORY_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_OUTPUT
          echo BUILD_TIME=$(date '+%y.%m%d.%H%M') >> $GITHUB_OUTPUT
      - name: Build with Gradle
        run: ./gradlew build
        env:
          BUILD_TIME: ${{ steps.setup.outputs.BUILD_TIME }}
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ github.event.repository.name }}-${{ steps.setup.outputs.BUILD_TIME }}"
          path: |
            build/libs/*.jar
            !build/libs/*-slim.jar
      - name: Publish to Maven
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'UpcraftLP/AxiomPatcher'
        run: ./gradlew publish
        env:
          BUILD_TIME: ${{ steps.setup.outputs.BUILD_TIME }}
          MAVEN_UPLOAD_URL: ${{ secrets.MAVEN_UPLOAD_URL }}
          MAVEN_UPLOAD_USERNAME: ${{ secrets.MAVEN_UPLOAD_USERNAME }}
          MAVEN_UPLOAD_PASSWORD: ${{ secrets.MAVEN_UPLOAD_PASSWORD }}
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && github.repository == 'UpcraftLP/AxiomPatcher'
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87 # v2.0.5
        with:
          # no wildcard here to prevent uploading the -slim jar to release assets
          files: |
            build/libs/AxiomPatcher-${{ steps.setup.outputs.BUILD_TIME }}.jar
          tag_name: ${{ steps.setup.outputs.BUILD_TIME }}
          name: ${{ steps.setup.outputs.BUILD_TIME }}
          generate_release_notes: true
          make_latest: true
